### ISSUE TITLE
NO DATA

### ISSUE THREAD

**Issue by Kingsmart75** [cedricp/ddt4all#685] opened 2022-05-23 13:14 UTC
hi I have a Smart Forfour 2019, I took an ELM327 USB with CHIP 25K80, I used DDT4ALL 2017 with its database and latest version here from November 2020 but I always get NO DATA in all sections, what can be the problem?

the CAN scan does not find any ECU in the box under the screen why? ELM fake?

- ELM327: https://www.ebay.it/itm/134107640073?hash=item1f39703109:g:db0AAOSwsaFic~JG
- I used STNTERM application with ATPPS command and this is the result:
ATPPS
ATPPS
00:FF F  01:FF F  02:FF F  03:32 F
04:01 F  05:FF F  06:F1 F  07:09 F
08:FF F  09:00 F  0A:0A F  0B:FF F
0C:68 F  0D:0D F  0E:FF F  0F:FF F
10:0D F  11:00 F  12:FF F  13:32 F
14:FF F  15:FF F  16:FF F  17:92 F
18:00 F  19:FF F  1A:FF F  1B:FF F
1C:FF F  1D:FF 

Is the CHIP original?

Folder Logs DDT4ALL:
[screens.txt](https://github.com/cedricp/ddt4all/files/8754740/screens.txt)

ELM BENCHMARK
DDT4ALL 2017:
v1.0 ATZ [OK]
v1.0 ATE1 [OK]
v1.0 ATL0 [OK]
v1.0 ATI [OK]
v1.0 AT@1 [OK]
v1.0 ATAL [OK]
v1.0 ATBD [OK]
v1.0 ATBI [OK]
v1.0 ATCAF0 [OK]
v1.0 ATCFC1 [OK]
v1.0 ATCP 01 [OK]
v1.0 ATCS [OK]
v1.0 ATCV 1250 [OK]
v1.0 ATD [OK]
v1.0 ATDP [OK]
v1.0 ATDPN [OK]
v1.0 ATH0 [OK]
v1.0 ATI [OK]
v1.0 ATIB 10 [OK]
v1.0 ATIB 96 [OK]
v1.0 ATL1 [OK]
v1.0 ATM0 [OK]
v1.0 ATMA [OK/TIMEOUT]
v1.0 ATMR 01 [OK/TIMEOUT]
v1.0 ATMT 01 [OK/TIMEOUT]
v1.0 ATNL [OK/TIMEOUT]
v1.0 ATPC [OK]
v1.0 ATR1 [OK]
v1.0 ATRV [OK]
v1.0 ATSH 001122 [OK]
v1.0 ATSH 012 [OK]
v1.0 ATSP A6 [OK]
v1.0 ATSP 6 [OK]
v1.0 ATCM 123 [OK]
v1.0 ATCM 12345678 [OK]
v1.0 ATCF 123 [OK]
v1.0 ATCF 12345678 [OK]
v1.0 ATST FF [OK]
v1.0 ATSW 96 [OK]
v1.0 ATSW 34 [OK]
v1.0 ATTP A6 [OK]
v1.0 ATTP 6 [OK]
v1.0 ATWM 817AF13E [OK]
v1.0 ATWS [OK]
v1.1 ATFC SD 300000 [OK]
v1.1 ATFC SH 012 [OK]
v1.1 ATFC SH 00112233 [OK]
v1.1 ATFC SM 1 [OK]
v1.1 ATPP FF OFF [OK]
v1.1 ATPP FF ON [OK]
v1.1 ATPPS [OK/TIMEOUT]
v1.2 ATAR [OK]
v1.2 ATAT1 [OK]
v1.2 ATDM1 [FAIL]
v1.2 ATIFR H [OK]
v1.2 ATIFR0 [OK]
v1.2 ATIIA 01 [OK]
v1.2 ATKW0 [OK]
v1.2 ATMP 0123 [FAIL]
v1.2 ATMP 0123 4 [FAIL]
v1.2 ATMP 012345 [FAIL]
v1.2 ATMP 012345 6 [FAIL]
v1.2 ATSR 01 [OK]
v1.3 ATCRA 012 [OK]
v1.3 ATCRA 01234567 [OK]
v1.3 ATD0 [OK]
v1.3 ATFE [OK]
v1.3 ATJE [OK]
v1.3 ATJS [OK]
v1.3 ATKW [OK]
v1.3 ATRA 01 [OK]
v1.3 ATS1 [OK/TIMEOUT]
v1.3 ATSP 00 [OK]
v1.3 ATV0 [OK]
v1.4 ATCEA [OK]
v1.4 ATCEA 01 [OK]
v1.4 ATCV 0000 [OK]
v1.4 ATIB 48 [OK]
v1.4 ATIGN [OK]
v1.4 ATPB 01 23 [OK]
v1.4 ATRD [OK]
v1.4 ATSD 01 [OK]
v1.4 ATSI [FAIL]
v1.4 ATFI [FAIL]
v1.4 ATSS [OK]
v1.4 ATTA 12 [OK]
v1.4 ATCSM1 [OK]
v1.4 ATJHF1 [OK]
v1.4 ATJTM1 [OK]
v1.4 ATJTM5 [OK]
v1.4b ATCRA [OK]
v2.0 ATAMC [OK]
v2.0 ATAMT 20 [OK]
v2.1 ATCTM1 [OK]
v2.1 ATCTM5 [OK]
Incompatible adapter on ARM core 
Result: 88 succeeded from 95
ELM Max version:v2.1 

DDT4ALL 2020
v1.0 ATZ [OK]
v1.0 ATE1 [OK]
v1.0 ATL0 [OK]
v1.0 ATI [OK]
v1.0 AT@1 [OK]
v1.0 ATAL [OK]
v1.0 ATBD [OK]
v1.0 ATBI [OK]
v1.0 ATCAF0 [OK]
v1.0 ATCFC1 [OK]
v1.0 ATCP 01 [OK]
v1.0 ATCS [OK]
v1.0 ATCV 1250 [OK]
v1.0 ATD [OK]
v1.0 ATDP [OK]
v1.0 ATDPN [OK]
v1.0 ATH0 [OK]
v1.0 ATI [OK]
v1.0 ATIB 10 [OK]
v1.0 ATIB 96 [OK]
v1.0 ATL1 [OK]
v1.0 ATM0 [OK]
v1.0 ATMA [OK/TIMEOUT]
v1.0 ATMR 01 [OK/TIMEOUT]
v1.0 ATMT 01 [OK/TIMEOUT]
v1.0 ATNL [OK/TIMEOUT]
v1.0 ATPC [OK]
v1.0 ATR1 [OK]
v1.0 ATRV [OK]
v1.0 ATSH 001122 [OK]
v1.0 ATSH 012 [OK]
v1.0 ATSP A6 [OK]
v1.0 ATSP 6 [OK]
v1.0 ATCM 123 [OK]
v1.0 ATCM 12345678 [OK]
v1.0 ATCF 123 [OK]
v1.0 ATCF 12345678 [OK]
v1.0 ATST FF [OK]
v1.0 ATSW 96 [OK]
v1.0 ATSW 34 [OK]
v1.0 ATTP A6 [OK]
v1.0 ATTP 6 [OK]
v1.0 ATWM 817AF13E [OK]
v1.0 ATWS [OK]
v1.1 ATFC SD 300000 [OK]
v1.1 ATFC SH 012 [OK]
v1.1 ATFC SH 00112233 [OK]
v1.1 ATFC SM 1 [OK]
v1.1 ATPP FF OFF [OK]
v1.1 ATPP FF ON [OK]
v1.1 ATPPS [OK/TIMEOUT]
v1.2 ATAR [OK]
v1.2 ATAT1 [OK]
v1.2 ATDM1 [FALLITO]
v1.2 ATIFR H [OK]
v1.2 ATIFR0 [OK]
v1.2 ATIIA 01 [OK]
v1.2 ATKW0 [OK]
v1.2 ATMP 0123 [FALLITO]
v1.2 ATMP 0123 4 [FALLITO]
v1.2 ATMP 012345 [FALLITO]
v1.2 ATMP 012345 6 [FALLITO]
v1.2 ATSR 01 [OK]
v1.3 ATCRA 012 [OK]
v1.3 ATCRA 01234567 [OK]
v1.3 ATD0 [OK]
v1.3 ATFE [OK]
v1.3 ATJE [OK]
v1.3 ATJS [OK]
v1.3 ATKW [OK]
v1.3 ATRA 01 [OK]
v1.3 ATS1 [OK/TIMEOUT]
v1.3 ATSP 00 [OK]
v1.3 ATV0 [OK]
v1.4 ATCEA [OK]
v1.4 ATCEA 01 [OK]
v1.4 ATCV 0000 [OK]
v1.4 ATIB 48 [OK]
v1.4 ATIGN [OK]
v1.4 ATPB 01 23 [OK]
v1.4 ATRD [OK]
v1.4 ATSD 01 [OK]
v1.4 ATSI [FALLITO]
v1.4 ATFI [FALLITO]
v1.4 ATSS [OK]
v1.4 ATTA 12 [OK]
v1.4 ATCSM1 [OK]
v1.4 ATJHF1 [OK]
v1.4 ATJTM1 [OK]
v1.4 ATJTM5 [OK]
v1.4b ATCRA [OK]
v2.0 ATAMC [OK]
v2.0 ATAMT 20 [OK]
v2.1 ATCTM1 [OK]
v2.1 ATCTM5 [OK]
Adattatore non compatibile basato su core ARM 
Risultato: 88 completato da 95
Versione max ELM:v2.1

Please help me!!!

**Comment by AndyIreland** [comment] 2022-05-23 14:36
what parameters are you trying to adjust? normal ECU's in the car, or the multimedia parameters?

**Comment by Kingsmart75** [comment] 2022-05-23 14:42
Many thanks for your reply, normal ECU's try to install stop led and i get error on CDB... I want to modify lightning configuration.

**Comment by KarelSvo** [comment] 2022-05-23 18:26
> Adattatore non compatibile basato su core ARM

Your Elm Interface is the problem.

https://it.aliexpress.com/item/32817153055.html

**Comment by Kingsmart75** [comment] 2022-05-23 20:33
> > Adattatore non compatibile basato su core ARM
> 
> Your Elm Interface is the problem.
> 
> https://it.aliexpress.com/item/32817153055.html

thanks for the reply, so mine is not compatible but the chip is right from the datasheet ... then it's a fake ... Why? How do know It?
 can you recommend another one to take on amazon so that if it doesn't work I can return it?  i saw these: 

https://www.amazon.it/dp/B09SZ7HZNW/ref=cm_sw_r_apan_i_2B4HSHGEDPGNHXHRSVS9?_encoding=UTF8&psc=1

https://www.amazon.it/dp/B01NAQ2878/ref=cm_sw_r_apan_i_2875GGKGQFR5JXQRX455?_encoding=UTF8&psc=1

Please help me!
Thanks

**Comment by AndyIreland** [comment] 2022-05-23 20:49
I am using the Bluetooth ELM327 Kingbolen fine with DDT4ALL this last year or so: 
here I split it open:

![280682433_359132939544260_919141663958541429_n](https://user-images.githubusercontent.com/49172217/169903664-e5087af8-9c6f-4216-9e8d-9c548f3dc52a.jpg)
![281829115_378922790865496_3727395958715371970_n](https://user-images.githubusercontent.com/49172217/169903667-c508107a-47f4-43a9-8fcf-d2e54525ce1a.jpg)

**Comment by Kingsmart75** [comment] 2022-05-23 21:52
Is this ok?
https://www.amazon.it/dp/B09KN3J6V6/ref=cm_sw_r_apan_i_FB03D42MHM0XKWTF78RC

**Comment by AndyIreland** [comment] 2022-05-23 22:12
> Is this ok? https://www.amazon.it/dp/B09KN3J6V6/ref=cm_sw_r_apan_i_FB03D42MHM0XKWTF78RC

well its wi-fi again ... any particular reason you are not going bluetooth dongle?

**Comment by Kingsmart75** [comment] 2022-05-24 07:29
> > Va bene? https://www.amazon.it/dp/B09KN3J6V6/ref=cm_sw_r_apan_i_FB03D42MHM0XKWTF78RC
> 
> beh è di nuovo wi-fi ... qualche motivo particolare per cui non stai andando al dongle bluetooth?

I do not have Bluetooth on my notebook, I should take USB Bluetooth adapter to connect ELM version of Bluetooth, wifi too fine or is it better to take Bluetooth?  Thanks for your suggestions.

**Comment by Kingsmart75** [comment] 2022-05-24 16:03
yes, it is an old Acer but it works very well, if your directions are to take Bluetooth adapter and ELM Bluetooth from your link it will be done !!!  I hope that a non-fake item arrives from China because I could not send it back by paying very high shipping costs.  Meanwhile, as with Amazon I can try and make it back I ordered Elm327 WiFi dollatech hoping that works while waiting for the Bluetooth model from China (1 month of waiting) ....

**Comment by Kingsmart75** [comment] 2022-05-27 08:35
here I am again with news ... waiting for the Bluetooth one from AliExpress.  the WiFi version arrived from Amazon but this also does not work or I am demented incapable and so on and so forth.  the program does not connect ... I put photos ... what could I check?

![IMG_20220527_101426](https://user-images.githubusercontent.com/106084607/170662892-277341cb-7582-41ac-9e2c-6df1f89f78a3.jpg)
![IMG_20220527_101737](https://user-images.githubusercontent.com/106084607/170662960-19c8bd36-f0c3-423f-8235-76586f582d88.jpg)
![IMG_20220527_101818](https://user-images.githubusercontent.com/106084607/170662984-c4c43364-0b32-426f-b0a6-e9379de5705d.jpg)
![IMG_20220527_101916](https://user-images.githubusercontent.com/106084607/170663048-aeae6a7e-cc45-4a08-8b32-54d36033b6e1.jpg)

**Comment by Kingsmart75** [comment] 2022-05-27 17:45
news ... I tried with the ecu tweaker android and tested with elm327test, I can read the parameters of the control unit but when I go to modify and click on SEND it tells me service not available, what can it be?  where am i wrong?  is it the fault of the elm327 WiFi?
[ELM327_Identifier_log0.txt](https://github.com/cedricp/ddt4all/files/8788790/ELM327_Identifier_log0.txt)
![Screenshot_2022-05-27-19-33-18-159_org quark dr canapp](https://user-images.githubusercontent.com/106084607/170763594-f66ca396-8054-4e34-9507-389cdddff58a.jpg)
![Screenshot_2022-05-27-19-39-34-692_org quark dr canapp](https://user-images.githubusercontent.com/106084607/170763607-4d0391c9-0001-480c-8a8d-57abda1762af.jpg)

**Comment by AndyIreland** [comment] 2022-05-28 21:01
I have never got the EMM lighting section to work on ECU TWEAKER - so I have  always used DDT4ALL to change EMM exterior lighting ECU

**Comment by Kingsmart75** [comment] 2022-05-28 21:51
> I have never got the EMM lighting section to work on ECU TWEAKER - so I have always used DDT4ALL to change EMM exterior lighting ECU

thank you very much for your support, with DDT4ALL why not connect the elm327 WiFi?  is this also false?  the test done with the elm327test app that I attached the log says something about the chip if good or not?  am I wrong something?

about android ecu-tweaker the app detects the Emm control unit by clicking on automatic detection and I see emm-lighting configuration, why doesn't SEND work and says service not available?  thanks for helping me ...

**Comment by AndyIreland** [comment] 2022-05-28 22:18
I just prefer my Kingbolen Bluetooth one wiyh correct PIC chip and it has worked fine for changing parameters , plus with BT ELM instead of wifi ELM - I can still browse internet from the home router on my laptop - if I use a WiFi dongle it cuts off the wifi from the rouuter because I have to connect the wifi elm through the laptop's wifi

**Comment by Furtif** [comment] 2022-05-28 23:28
this work fine https://www.elm327.fr/

**Comment by KarelSvo** [comment] 2022-05-29 06:23
> with DDT4ALL why not connect the elm327 WiFi? is this also false? 

give me your ddt4all installation file, i will test my kingbolen wifi with it

**Comment by Kingsmart75** [comment] 2022-05-29 12:11
> > with DDT4ALL why not connect the elm327 WiFi? is this also false?
> 
> give me your ddt4all program folder, i will test my kingbolen wifi with it

thanks for your support to my problem, I tried to use 2 versions of DDT4ALL software, one of 2017 taken from the Smart Italia forum http://www.smart-forum.it/forum/topic/44376-software-ddt4all-e-driver/ with dt2000 db of 2017 and placed on the ECUS folder inside DDT4ALL, another version downloaded here and with the same db of 2017, I also tried other db taken on other forums of versions DDT4ALL 5.4 db 02-2019 and DDT4ALL 5.5 db 07- 2019.  am I wrong to put the db?  but it is the program in both versions that does not connect to the ELM WiFi as shown in the photo I attached above.  in any case I have to zip my DDT4ALL folder and attach it here?

**Comment by Kingsmart75** [comment] 2022-05-29 12:17
> this work fine https://www.elm327.fr/ DTT4ALL/pyren etc..
> 
> https://www.elm327.fr/logiciel-elm327/ https://play.google.com/store/apps/details?id=org.eobdfacile.android&hl=fr&gl=US https://play.google.com/store/apps/details?id=com.ovz.carscanner&hl=fr&gl=US also for iOS as same names..

thanks, I saw but I think they do not ship to Italy, it says shipping to France, Belgium, Switzerland and DOM-TOM ... I would like to understand if my elm327 WiFi I got is valid or even this fake ... or with ecu-tweaker or other app is there a way to make changes to the EMM lightning configuration control units reads on Android?

**Comment by Kingsmart75** [comment] 2022-05-29 12:28
> I just prefer my Kingbolen Bluetooth one wiyh correct PIC chip and it has worked fine for changing parameters , plus with BT ELM instead of wifi ELM - I can still browse internet from the home router on my laptop - if I use a WiFi dongle it cuts off the wifi from the rouuter because I have to connect the wifi elm through the laptop's wifi

I believe you, I also ordered the Bluetooth one from AliExpress from the link recommended here, it will arrive in about 20 days, in the meantime I also wanted to try with the WiFi one taken from Amazon and always of the same kingbolen brand, now I wanted to understand if this WiFi is fake or is it me mentally retarded that I can't get it going because I'm doing something wrong?  my notebook has windows 11 is he the problem?  I would also have a 12" atom 2gb RAM netbook with Windows 10 32bit but it's slow as hell ... With this I only tried with the fake version with the USB cable ...

**Comment by KarelSvo** [comment] 2022-05-29 20:11
I could not reproduce your problem with Kingbolen Wifi ddt4all 5.5.0. I have no connection problem on Win7.

You connect your Wifi Elm to the network. Open an internet browser and write in the browser address 192.168.0.10:35000 or http://192.168.0.10:35000, not https://192.168.0.10:35000 and confirm.
Do you then have connection to the Wifi Elm?

**Comment by Furtif** [comment] 2022-05-30 16:12
> thanks, I saw but I think they do not ship to Italy, it says shipping to France, Belgium, Switzerland and DOM-TOM ... I would like to understand if my elm327 WiFi I got is valid or even this fake ... or with ecu-tweaker or other app is there a way to make changes to the EMM lightning configuration control units reads on Android?
works with pyren android ddt4all tweak, and with the apk i mentioned above available for ios/android works with pyren on pc or ddt4all pc equally

**Comment by Kingsmart75** [comment] 2022-05-30 16:39
> > thanks, I saw but I think they do not ship to Italy, it says shipping to France, Belgium, Switzerland and DOM-TOM ... I would like to understand if my elm327 WiFi I got is valid or even this fake ... or with ecu-tweaker or other app is there a way to make changes to the EMM lightning configuration control units reads on Android?
> 
> works with pyren android ddt4all tweak, and with the apk i mentioned above available for ios/android works with pyren on pc or ddt4all pc equally

thanks again for your support, sorry but I can't understand well, those two links you put above related to android apps allow you to change parameters like DDT4ALL?  then taking apk indicated to you through the Android smartphone with my elm327 can go EMM lightning configuration and enable the use of LED have no error on board computer?  can you explain better please?

**Comment by Furtif** [comment] 2022-05-30 16:55
> 

this one at least in renault has a codage page https://play.google.com/store/apps/details?id=com.ovz.carscanner&hl=fr&gl=US the other has a way to correct errors I have the free version maybe the paying one has more things, in pyren apk or clip+xxx apk you can change a lot of things as well as tweak apk (or computer version) only inconvenience you don't have access to the multimedia part as access to medianav for that you need a correct usb cable like this http://www.derelek.com/nos-produits/ better is USB-Diag 3) or a bosh probe compatible with ddt2000 these 2 are both compatible with ddt2000 with access to everything, every other obd2 typo at least in renault only has access to abs engine part airbaig dashboard board etc.

**Comment by Furtif** [comment] 2022-05-30 16:57
but there are many other apk in playstore like https://play.google.com/store/apps/details?id=com.palmerperformance.DashCommand&hl=fr&gl=US etc a lot of them

**Comment by Kingsmart75** [comment] 2022-05-30 17:09
excuse me, please i am fused, i have seen all these APK but which one is same as DDT4ALL? I am not interested in multimedia, I want to change the parameters of the control units as with DDT4ALL, sorry again but these APKs only seem to read the parameters and eliminate errors they do not allow you to enter and make changes or I do not understand anything ...

**Comment by Furtif** [comment] 2022-05-30 17:35
> excuse me, please i am fused, i have seen all these APK but which one is same as DDT4ALL? I am not interested in multimedia, I want to change the parameters of the control units as with DDT4ALL, sorry again but these APKs only seem to read the parameters and eliminate errors they do not allow you to enter and make changes or I do not understand anything ...


Lol 😂 no need to be confused, I already answered you above what I have I bought there on the elm327.fr website I bought the usb+ Wi-Fi version it works perfectly, now the rest I said usb diag 3 etc this is the cable that does everything in nissan Renault dacia se the multimedia part doesn't interest you don't need a cable like that a bon obdII arrives perfectly.

**Comment by Kingsmart75** [comment] 2022-05-30 17:43
> > excuse me, please i am fused, i have seen all these APK but which one is same as DDT4ALL? I am not interested in multimedia, I want to change the parameters of the control units as with DDT4ALL, sorry again but these APKs only seem to read the parameters and eliminate errors they do not allow you to enter and make changes or I do not understand anything ...
> 
> Lol 😂 no need to be confused, I already answered you above what I have I bought there on the elm327.fr website I bought the usb+ Wi-Fi version it works perfectly, now the rest I said usb diag 3 etc this is the cable that does everything in nissan Renault dacia if the multimedia part doesn't interest you don't need a cable like that a good obd II arrives perfectly.

ok that's clear, your ELM327 works, lucky you!!! But as for the applications what can I use as an alternative to DDT4ALL (to modify the EMM ECU parameters for the lights and cornering and other things like Km \ L instead of L \ 100km, no multimedia I am not interested maybe only enable android mirror in the very case remote) since I can't get it to work and it seems that my ELM327 wifi kingbolen is good?

**Comment by KarelSvo** [comment] 2022-05-30 19:12
You should run a test in the internet browser to narrow down your problem.
ddt4all 5.5.0 works in general
Your Wifi Kingbolen works too, tested on ecutweaker.
But there is a mistake hiding somewhere.

**Comment by Kingsmart75** [comment] 2022-05-31 08:46
Only in Firefox and with app elm327test 
running i see this about 192.168.0.10:35000
GET / HTTP/1.1
?

>t: 192.168.0.10:35000
?

>er-Agent: Mozilla/5.0 (Android 12; Mobile; rv:100.0) Gecko/100.0 Firefox/100.0
?

>ept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
?

>cept-Language: it-IT
?

>ept-Encoding: gzip, deflate
?

>nnection: keep-alive
?

>rade-Insecure-Requests: 1
?

>ATZ
ü

OBDII  v1.5

>AT@1
OBDII to RS232 Interpreter

>ATSPA6
OK

>ATTPA6
OK

>ATTP6
OK

>ATSP00
OK

>ATSP6
OK

>ATAL
OK

>ATNL
OK

>ATAMC
?

>ATAMT20
?

>ATRA70
OK

>ATSR70
OK

>ATAR
OK

>ATAT0
OK

>ATAT2
OK

>ATAT1
OK

>ATBD
0C 00 00 07 6D 03 7F 3E 12 00 00 00 00 

>ATBRT0F
OK

>ATC0
?

>ATC1
?

>ATCAF0
OK

>ATCAF1
OK

>ATCEA04
OK

>ATCERF1
?

>ATCEA
OK

>ATCF00000111
OK

>ATCF111
OK

>ATCFC0
OK

>ATCFC1
OK

>ATCM00000111
OK

>ATCM111
OK

>ATCP18
OK

>ATCRA7C0
OK

>ATCRA000007C0
OK

>ATCRA
?

>ATCS
T:00 R:00 

>ATCSM0
?

>ATCSM1
?

>ATCTM5
?

>ATCTM1
?

>ATCV0000
OK

>ATD1
OK

>ATD0
OK

>ATDP
ISO 15765-4 (CAN 11/500)

>ATDPN
6

>ATE0
OK

>OK

>ATFCSD001122
OK

>ATFCSH000007B0
OK

>ATFCSH7B0
OK

>ATFCSM1
OK

>ATFCSM2
OK

>ATFCSM8
?

>ATFCSM9
?

>ATFCSMA
?

>ATFCSM0
OK

>ATFE
OK

>ATFT10
?

>ATFT
?

>ATH0
OK

>ATH1
OK

>ATI
OBDII  v1.5

>ATIA
?

>ATIB10
OK

>ATIB12
?

>ATIB15
?

>ATIB48
OK

>ATIB96
OK

>ATIFRS
OK

>ATIFRH
OK

>ATIFR0
OK

>ATIFR2
OK

>ATIFR1
OK

>ATIFR6
?

>ATIFR5
?

>ATIFR4
?

>ATIGN
ON

>ATIIA7A
OK

>ATJS
OK

>ATJE
OK

>ATJHF0
?

>ATJHF1
?

>ATJTM5
?

>ATJTM1
?

>ATKW
1:-- 2:--

>ATKW0
OK

>ATKW1
OK

>ATL0
OK

>ATL1
OK

>ATM1
OK

>ATM0
OK

>ATPPFFON
OK

>ATPPFFOFF
OK

>ATPPS
00:FF F  01:FF F  02:FF F  03:32 F
04:01 F  05:FF F  06:F1 F  07:09 F
08:FF F  09:00 F  0A:0A F  0B:FF F
0C:68 F  0D:0D F  0E:9A F  0F:FF F
10:0D F  11:00 F  12:FF F  13:32 F
14:FF F  15:0A F  16:FF F  17:92 F
18:00 F  19:28 F  1A:FF F  1B:FF F
1C:FF F  1D:FF F  1E:FF F  1F:FF F
20:FF F  21:FF F  22:FF F  23:FF F
24:00 F  25:00 F  26:00 F  27:FF F
28:FF F  29:FF F  2A:38 F  2B:02 F
2C:E0 F  2D:04 F  2E:80 F  2F:0A F

>ATR0
OK

>ATR1
OK

>ATRV
11.7V

>ATS0
OK

>ATS1
OK

>ATSDFF
OK

>ATRD
FF 

>ATSH000007E0
?

>ATSHA848F1
OK

>ATSH7B0
OK

>ATST32
OK

>ATSWFF
OK

>ATTAF9
OK

>ATV1
OK

>ATV0
OK

>ATWMC133F13E
OK

>ATPC
OK

>ATWS


OBDII  v1.5

>ATD

OK

>ATZ
ü

OBDII  v1.5

>

**Comment by Furtif** [comment] 2022-05-31 16:15
> if i want to try pyren windows or pyclip android where can i find it? with database included? can i use my elm327 wifi? Thanks again for everything

Do you have discord, telegram or other?

**Comment by Kingsmart75** [comment] 2022-05-31 16:43
> > if i want to try pyren windows or pyclip android where can i find it? with database included? can i use my elm327 wifi? Thanks again for everything
> 
> Do you have discord, telegram or other?

telegram

**Comment by Furtif** [comment] 2022-05-31 16:46
https://t.me/Furtif

**Comment by KarelSvo** [comment] 2022-05-31 19:57
[PyCLIP.apk](https://transfiles.ru/hjl38)

**Comment by Furtif** [comment] 2022-06-05 00:15
if ok @Kingsmart75 close the issue in this repo as  a lot close all solve please.

**Closed** 2022-06-06 10:28 UTC

**Comment by Kingsmart75** [comment] 2022-06-06 10:29
FAKE ELM327 USB

**Comment by Mr-Pingu** [comment] 2025-04-11 07:39
> I have never got the EMM lighting section to work on ECU TWEAKER - so I have always used DDT4ALL to change EMM exterior lighting ECU

I use Vgate Icar pro WLAN adapter, on windows it doesn't work at all but on ECU tweaker I can reach AND write lot of ECUs but not EMM

Same, all other units work but in ECU-Tweaker I just get NO DATA.
Below log example of first trying EMM_EDISON module and then later T4_BCM module, while this one has only partial match though. 


`CAN SENT: [11-04-07:50:15] 10C0
CAN RECV: [11-04-07:50:15] ERROR : 0210C0
NO DATA
​
​
CAN SENT: [11-04-07:50:17] 2180
CAN RECV: [11-04-07:50:17] ERROR : 022180
NO DATA
​
​
CAN SENT: [11-04-07:50:19] 1003
CAN RECV: [11-04-07:50:19] ERROR : 021003
NO DATA
​
​
CAN SENT: [11-04-07:50:21] 22F1A0
CAN RECV: [11-04-07:50:21] ERROR : 0322F1A0
NO DATA
​
​
CAN SENT: [11-04-07:50:22] 22F18A
CAN RECV: [11-04-07:50:22] ERROR : 0322F18A
NO DATA
​
​
CAN SENT: [11-04-07:50:23] 22F194
CAN RECV: [11-04-07:50:23] ERROR : 0322F194
NO DATA
​
​
CAN SENT: [11-04-07:50:31] 10C0
CAN RECV: [11-04-07:50:31] 50C0
CAN SENT: [11-04-07:50:31] 2180
CAN RECV: [11-04-07:50:31] 6180313836375204303031303030303014190B600B6002010088
New session with ECU T4_BCM_DDT2000_SW11_0`
